-- CreateTable
CREATE TABLE "LakeSubmission" (
    "id" TEXT NOT NULL,
    "userId" TEXT,
    "status" TEXT NOT NULL DEFAULT 'pending',
    "name" TEXT NOT NULL,
    "slug" TEXT NOT NULL,
    "description" TEXT NOT NULL,
    "ownerType" TEXT NOT NULL,
    "fishingType" TEXT NOT NULL,
    "fish" TEXT NOT NULL,
    "lat" DOUBLE PRECISION NOT NULL,
    "lng" DOUBLE PRECISION NOT NULL,
    "street" TEXT NOT NULL,
    "city" TEXT NOT NULL,
    "postalCode" TEXT NOT NULL,
    "voivodeship" TEXT NOT NULL,
    "area" TEXT,
    "averageDepth" TEXT,
    "bottomType" TEXT,
    "waterType" TEXT,
    "cottages" BOOLEAN NOT NULL DEFAULT false,
    "campfire" BOOLEAN NOT NULL DEFAULT false,
    "noKill" BOOLEAN NOT NULL DEFAULT false,
    "tent" BOOLEAN NOT NULL DEFAULT false,
    "parking" BOOLEAN NOT NULL DEFAULT false,
    "pier" BOOLEAN NOT NULL DEFAULT false,
    "toilet" BOOLEAN NOT NULL DEFAULT false,
    "shop" BOOLEAN NOT NULL DEFAULT false,
    "nightFishing" BOOLEAN NOT NULL DEFAULT false,
    "boatRental" BOOLEAN NOT NULL DEFAULT false,
    "contactName" TEXT,
    "contactPhone" TEXT,
    "contactEmail" TEXT,
    "contactWebsite" TEXT,
    "adminNote" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "LakeSubmission_pkey" PRIMARY KEY ("id")
);
