import type { CatchFilterState, CatchFormState } from "@/components/catches/types";

export const INITIAL_CATCH_FORM_STATE: CatchFormState = {
  fishName: "",
  customFishName: "",
  weight: "",
  length: "",
  method: "spinning",
  bait: "",
  caughtAt: "",
  lakeId: "",
  tripId: "",
  note: "",
  isPublic: false,
};

export const INITIAL_CATCH_FILTERS: CatchFilterState = {
  search: "",
  method: "all",
  species: "all",
  status: "all",
  lakeId: "all",
  tripId: "all",
  fromDate: "",
  toDate: "",
};

export const CATCH_METHODS = [
  { label: "Spinning", value: "spinning" },
  { label: "Feeder", value: "feeder" },
  { label: "Method feeder", value: "method_feeder" },
  { label: "Karpiówka", value: "carp" },
  { label: "Spławik", value: "float" },
  { label: "Muchówka", value: "fly" },
  { label: "Inna", value: "other" },
] as const;

export const CATCH_STATUS_OPTIONS = [
  { label: "Wszystkie statusy", value: "all" },
  { label: "Prywatne", value: "private" },
  { label: "W weryfikacji", value: "pending" },
  { label: "W rankingu", value: "approved" },
  { label: "Odrzucone", value: "rejected" },
] as const;

export const FISH_SPECIES_OPTIONS = [
  "Amur biały",
  "Boleń",
  "Brzana",
  "Certa",
  "Ciernik",
  "Cierniczek",
  "Czebaczek amurski",
  "Głowacica",
  "Jaź",
  "Jazgarz",
  "Jelec",
  "Jesiotr",
  "Karaś pospolity",
  "Karaś srebrzysty",
  "Karp",
  "Kiełb",
  "Kleń",
  "Koza",
  "Krąp",
  "Leszcz",
  "Lin",
  "Lipień",
  "Łosoś atlantycki",
  "Miętus",
  "Okoń",
  "Piekielnica",
  "Piskorz",
  "Płoć",
  "Pstrąg potokowy",
  "Pstrąg tęczowy",
  "Pstrąg źródlany",
  "Różanka",
  "Sandacz",
  "Sieja",
  "Sielawa",
  "Słonecznica",
  "Strzebla potokowa",
  "Sum",
  "Sumik karłowaty",
  "Szczupak",
  "Śliz",
  "Świnka",
  "Tołpyga biała",
  "Tołpyga pstra",
  "Troć wędrowna",
  "Ukleja",
  "Węgorz europejski",
  "Wzdręga",
] as const;
